import { extendTheme } from '@chakra-ui/react';
import { mode } from '@chakra-ui/theme-tools';

const breakpoints = {
  sm: '30em', // 480px
  md: '632px',
  lg: '62em',
  xl: '80em',
  '2xl': '96em',
};

export const theme = extendTheme({
  colors: {
    // Generated by https://palette.saas-ui.dev/
    primary: {
      '50': '#fdf5fb',
      '100': '#f8d7ed',
      '200': '#f2b2dd',
      '300': '#ea83c8',
      '400': '#e665ba',
      '500': '#ce49a1',
      '600': '#ae3e88',
      '700': '#8c326e',
      '800': '#772a5d',
      '900': '#561e43',
    },
    gray: {
      '50': '#F2F2F2',
      '100': '#DBDBDB',
      '200': '#C4C4C4',
      '300': '#ADADAD',
      '400': '#969696',
      '500': '#808080',
      '600': '#666666',
      '700': '#4D4D4D',
      '800': '#333333',
      '900': '#1A1A1A',
    },
  },
  breakpoints,
  sizes: {
    container: breakpoints,
  },
  styles: {
    global: (props: any) => ({
      '*, *::before, *::after': {
        boxSizing: 'border-box',
      },
      a: {
        textUnderlineOffset: '2px',
      },
      body: {
        bg: mode('white', '#222')(props),
      },
    }),
  },
  components: {
    Button: {
      baseStyle: {
        borderRadius: '8px',
      },
      sizes: {
        md: {
          fontSize: 'sm',
        },
      },
    },
  },
});
