// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { AccountId32 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi> extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x184de1e97d8dba311c74fa923646f3bb4c5b0b4f747447857dbe70305dcd777e
   **/
  Greeted: GenericContractEvent<
    'Greeted',
    {
      /**
       *
       * @indexed: false
       **/
      from: AccountId32 | undefined;
      /**
       *
       * @indexed: false
       **/
      message: string;
    }
  >;
}
