name: E2E Zombienet Tests

on:
  push:
  workflow_dispatch:
  merge_group:

jobs:
  zombienet-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - name: Download executables
        run: |
          curl -L -O https://github.com/paritytech/zombienet/releases/download/v1.3.116/zombienet-linux-x64
          chmod +x zombienet-linux-x64
          
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.14.1/polkadot
          chmod +x polkadot
          
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.14.1/polkadot-execute-worker
          chmod +x polkadot-execute-worker
          
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.14.1/polkadot-prepare-worker
          chmod +x polkadot-prepare-worker
          
          curl -L -O https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.14.1/polkadot-parachain
          chmod +x polkadot-parachain
      - name: Spawn network
        run: |
          export PATH=$(pwd):$PATH
          export RUST_BACKTRACE=full
          ./zombienet-linux-x64 -p native spawn ./e2e/zombienet/networks.json &
          
          chmod +x ./e2e/zombienet/wait-for-port.sh
          ./e2e/zombienet/wait-for-port.sh 9933 30
          ./e2e/zombienet/wait-for-port.sh 9944 30
      - name: Run tests
        run: yarn workspace zombienet run e2e:test
